### ISSUE TITLE
Добавить конфиг postcss

### ISSUE THREAD

**Issue by Nitive** [hexlet-volunteers/interviews#23]
Стандартный набор: autoprefixer, precss, cssnext.

**Comment by sashashakun** [comment]
Я не использую postcss и не очень понимаю зачем он нам, если будем использовать бутстрап. Этот набор плагинов это ок?

**Comment by Nitive** [comment]
Аutoprefixer всё равно нужен, не писать же префиксы руками. Особенно для флексов.
precss - поддержка переменных, нестинга, циклы, условия.
cssnext - поддержка новых спецификаций.

**Comment by alexander37137** [comment]
Беру на себя
