### ISSUE TITLE
View layer with Bootstrap 4

### ISSUE THREAD

**Issue by sashashakun** [hexlet-volunteers/interviews#26]
Берем [Bootstrap 4](http://v4-alpha.getbootstrap.com/) и делаем морду, предлагаю взять [вот этот](http://v4-alpha.getbootstrap.com/examples/cover/) шаблон целиком, сделать две кнопки вместо одной той что есть, как обсуждалось:

> Когда заходишь на сайт там две больших кнопки. Одна "хочу собеседовать", тыкаешь,заполняешь форму (город, должность и где работает) и ждешь писем. Другие тыкают “хочу собеседоваться" (город, по каким языкам)

Прикрутить туда [модальные окна](http://v4-alpha.getbootstrap.com/components/modal/) с соответствующими полями, сделать скажем в правом верхнем углу кнопку авторизации через гитхаб.

Можно немного позаимствовать дизайн [отсюда](https://ru.hexlet.io/), если @mokevnin не против :)
В #25 нам запилили jade, так что давайте пилить на нем.

Вроде все.

**Comment by gldmtr** [comment]
Авторизация до нажатия кнопки ведь не нужна? Значит и кнопка должна находиться в самой модалке.

**Comment by sashashakun** [comment]
Согласен

**Comment by sashashakun** [comment]
Возьму на себя

**Comment by sashashakun** [comment]
[Ветка](https://github.com/sashashakun/interviews/tree/view) с заготовкой

**Comment by sashashakun** [comment]
Набросал тут, нет желающих продолжить? @sanykey @AlexMold ?
<img width="300" alt="2016-03-07 22 38 44" src="https://cloud.githubusercontent.com/assets/5776864/13580933/7adf0100-e4b5-11e5-81b6-62d8399b0f04.png">
<img width="300" alt="2016-03-07 22 38 53" src="https://cloud.githubusercontent.com/assets/5776864/13580937/80d5b504-e4b5-11e5-93fc-a739901bcd85.png">
<img width="300" alt="2016-03-07 22 39 00" src="https://cloud.githubusercontent.com/assets/5776864/13580943/84858e54-e4b5-11e5-9995-3e5072824c4b.png">

**Comment by AlexMold** [comment]
это дизайн?
Я возьмусь только надо .jade освоить(не работал с этим шаблонизатором).
Только объясните, как проект развернуть???
readme сделайте.

**Comment by sashashakun** [comment]
Это не дизайн, это скриншоты готовой верстки, инструкция будет

**Comment by sashashakun** [comment]
Jade тут: http://jade-lang.com/

**Comment by AlexMold** [comment]
@sashashakun что по ТЗ ещё сверстать нужно?

**Comment by sashashakun** [comment]
@AlexMold загляни в слак

**Comment by sashashakun** [comment]
closes via #62
