### ISSUE TITLE
Heroku. Define a Procfile.

### ISSUE THREAD

**Issue by andrew-ko** [hexlet-volunteers/interviews#36]
Use a Procfile, a text file in the root directory of your application, to explicitly declare what command should be executed to start your app.
Example:
`web: node index.js`
This declares a single process type, `web`, and the command needed to run it.

from: [Getting Started with Node.js on Heroku](https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-a-procfile)

**Comment by Nitive** [comment]
Heroku run `npm start` by default so we may do not write Procfile.

**Comment by andrew-ko** [comment]
ok. closed
