### ISSUE TITLE
Add named routes

### ISSUE THREAD

**Issue by sashashakun** [hexlet-volunteers/interviews#43]
https://github.com/alubbe/named-routes

**Comment by andrew-ko** [comment]
try to take it

**Comment by sashashakun** [comment]
@andrkvlnko почитай чатик вот с [этого](https://hexlet-ru.slack.com/archives/hexlet-volunteers/p1457194696001945) момента, и если возникнут вопросы, спрашивай.

**Comment by andrew-ko** [comment]
Чат почитал.
Что нужно сделать для закрытия этого issue?
Я подключил модуль 'named-routes', и единственный роут, по которому рендерится index.jade назвал `'home'`.

**Comment by sashashakun** [comment]
Мы c @gldmtr посмотрим, если все ок, смерджим PR и закроем issue.
