### ISSUE TITLE
Github Auth

### ISSUE THREAD

**Issue by Shamash2014** [hexlet-volunteers/interviews#51]
Regarding #2 . We need github auth, so we can use it to authenticate in our app.

**Comment by sashashakun** [comment]
@Shamash2014 do you want to take it?

**Comment by Shamash2014** [comment]
It would be great. I'll fix it when we will have db)

**Comment by sashashakun** [comment]
Great

**Comment by sashashakun** [comment]
@Shamash2014 it [this](https://github.com/gldmtr/interviews/commit/534e7e2c078b50c09aeb72b90f0c6d69d400810e) enough for adding auth ?

**Comment by Shamash2014** [comment]
Sure) It's enough)

**Comment by sashashakun** [comment]
@Shamash2014 I think we are ready to start work with this issue;) How much time do you need?

**Comment by Shamash2014** [comment]
I'll try to fix it today after work)

**Comment by sashashakun** [comment]
Great!

**Comment by sashashakun** [comment]
@Shamash2014 It would be great, if you will be more active in slack :)

**Comment by Shamash2014** [comment]
We are near the end)
