### ISSUE TITLE
Change repository to express-generator project structure

### ISSUE THREAD

**Issue by alexander37137** [hexlet-volunteers/interviews#55]
Переделать структуру проекта на структуру в стиле express-generator
http://expressjs.com/en/starter/generator.html
По умоланию express-generator генерит es5 код
Проще всего будет не перегенирировать весь проект, а переделать существующую структуру папок.
Весь код должен быть в es6, пример как это сделать: https://github.com/expressjs/generator/pull/89
При переезде не должны потеряться уже интегрированные фишечки такие как тесты, минкер, flow, etc

**Comment by alexander37137** [comment]
Беру на себя

**Comment by sashashakun** [comment]
@alexander37137 в какие сроки ты планируешь это реализовывать?

**Comment by alexander37137** [comment]
Сегодня - завтра
