### ISSUE TITLE
Fix email requirements

### ISSUE THREAD

**Issue by sashashakun** [hexlet-volunteers/interviews#86]
Now we can save users email, only if it open on github, like this 
![image](https://cloud.githubusercontent.com/assets/5776864/13905517/f2ab34a2-eed2-11e5-8cb0-1541b66b972e.png)
I think we should improve this, dont know best way, any ideas?

**Comment by gldmtr** [comment]
One of options - show modal window and ask something like "input your email" if we can't get email from git.

**Comment by sashashakun** [comment]
[WIP](https://github.com/sashashakun/interviews/tree/email-permission)
